services:
  postgres:
    image: postgres
    container_name: sistema_reembolso_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sistema_reembolso
    ports:
      - 5432:5432